---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mhelmlaravel.fullname" . }}-nginx-service
  labels:
    app: qutenza-svc
spec:
  selector:
    app: qutenza-svc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mhelmlaravel.fullname" . }}-nginx-deployment
  labels:
    app: qutenza-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qutenza-svc
  template:
    metadata:
      labels:
        app: qutenza-svc
    spec:
      volumes:
      - name: index-config
        configMap:
          name: index-config

      - name: nginx-config
        configMap:
          name: nginx-config

      containers:
      - name: nginx
        image: nginx:1.18.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: index-config
          mountPath: /var/www/public
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1
            memory: 600Mi
